[package]
name = "harvest"
version = "0.1.0"
authors = ["Venkatesh Duraiarasan <dev_venkat@outlook.com>"]

[dependencies]
rustc-serialize = "0.3"
toml = "0.2"
rusqlite = "0.8.0"
encoding = "0.2.33"
log = "0.3"

[dev-dependencies]
env_logger = "0.3"